# Generated by Django 4.2 on 2023-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_registered',
            name='Course_id',
            field=models.CharField(max_length=10),
        ),
    ]
