# Generated by Django 4.2 on 2023-04-19 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0002_alter_course_registered_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=25)),
                ('mDate', models.DateTimeField(null=True)),
                ('A_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_connect.student')),
                ('Mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_connect.mentor')),
            ],
        ),
    ]
