# Generated by Django 4.2 on 2023-04-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0003_mentormeetings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentorMeetings',
            new_name='MentorMeeting',
        ),
    ]
